*****************************************
Filename: ADSL.sas
Author: Moses Adetoro
Date: 3 June 2019
SAS: SAS 9.4 (TS2M0)
Platform: Windows XP
Project/Study: 765/15
Description: <To develop the SDTM VS Datasets>
Input: SDTM.DM SDTM.SUPPDM SDTM.VS SDTM.EX
Output: ADAM.ADSL
Macros Used: <No macros used>
------------------------------------------
MODIFICATION HISTORY:

<DD-MON-YYYY>, <Firstname Lastname>

<Description>
******************************************;
libname Raw "C:\PROJECT\QPS3\RAW";
libname SDTM "C:\PROJECT\QPS3\SDTM";
libname ADAM "C:\PROJECT\QPS3\ADAM";

/* COPY ALL VARIABLES FROM SDTM.DM DATASETS */;

DATA DM1;
SET SDTM.DM;
BY USUBJID;
RUN;

/*WE NEED TO MERGE WITH SUPPDM IF THERE IS ANY. TRANSPONSE SUPPDM DATASETS */;

PROC SORT DATA=SDTM.SUPPDM;
BY STUDYID USUBJID;
RUN;

PROC TRANSPOSE DATA=SDTM.SUPPDM OUT=SUPPDM_T (DROP=_NAME_ _LABEL_);
BY STUDYID USUBJID;
ID QNAM;
VAR QVAL;
IDLABEL QLABEL;
RUN;

DATA DM2;
MERGE DM1(IN=A) SUPPDM_T(IN=B);
BY USUBJID;
IF A;
RUN;

DATA HEIGHT WEIGHT BMI;
SET SDTM.VS;
IF VSTESTCD="HEIGHT" THEN OUTPUT HEIGHT;
IF VSTESTCD="WEIGHT" THEN OUTPUT WEIGHT;
IF VSTESTCD="BMI" THEN OUTPUT BMI;
KEEP STUDYID USUBJID VSORRES VSORRESU;
RUN;

DATA HEIGHT;
SET HEIGHT;
HEIGHT=INPUT(VSORRES, BEST.);
HEIGHTU=VSORRESU;
KEEP STUDYID USUBJID HEIGHT HEIGHTU;
RUN;

DATA WEIGHT;
SET WEIGHT;
WEIGHT=INPUT(VSORRES, BEST.);
WEIGHTU=VSORRESU;
KEEP STUDYID USUBJID WEIGHT WEIGHTU;
RUN;

DATA BMI;
SET BMI;
BMI=INPUT(VSORRES, BEST.);
BMIU=VSORRESU;
KEEP STUDYID USUBJID BMI BMIU;
RUN;

DATA DM3;
MERGE DM2(IN=A) HEIGHT WEIGHT BMI;
BY USUBJID;
IF A;
RUN;

/*EXPOSURE DATASET TO DERIVE TRT01A TRT02P*/


DATA EX1;
SET SDTM.EX_FINAL;
IF EXSEQ=1;
KEEP USUBJID EXTRT EXDOSE EXSTDTC EXENDTC;
RUN;

DATA EX2 (RENAME=(EXTRT=EXTRT2 EXDOSE=EXDOSE2 EXSTDTC=EXSTDTC2 EXENDTC=EXENDTC2));
SET SDTM.EX_FINAL;
IF EXSEQ=2;
KEEP USUBJID EXTRT EXDOSE EXSTDTC EXENDTC;
RUN;

DATA DM4;
MERGE DM3(IN=A) EX1 EX2;
BY USUBJID;
RUN;

