*****************************************
Filename: Vital_Signs.sas
Author: Moses Adetoro
Date: 25 April 2019
SAS: SAS 9.4 (TS2M0)
Platform: Windows XP
Project/Study: 765/15
Description: <To develop the SDTM VS Datasets>
Input: Raw.Vital_Signs
Output: SDTM.VS
Macros Used: <No macros used>
------------------------------------------
MODIFICATION HISTORY:

<DD-MON-YYYY>, <Firstname Lastname>

<Description>
******************************************;
libname Raw "C:\PROJECT\QPS3\RAW";
libname SDTM "C:\PROJECT\QPS3\SDTM";

/*Derived Vital Signs SDTM datasets*/

DATA VS;
SET Raw.Vital_Signs2;
STUDYID="765/15";
Domain="VS";
SUBJID=strip(SUBJID);
SITEID="001";
USUBJID=STRIP(STUDYID)||"-"||STRIP(SITEID)||"-"||STRIP(SUBJID);
VSDTC=PUT(RECDT, IS8601DA.)||"T"||PUT(RECDTM, TOD8.);
VSDTN=DATEPART(INPUT(VSDTC, IS8601DT.));
FORMAT VSDTN DATE10.;
RUN;

DATA VS1;
SET VS;
VSTPT=PROPCASE(TP);
IF VSTPT="Check-In" THEN VSTPTNUM=1;
ELSE IF VSTPT="0" THEN VSTPTNUM=2;
ELSE IF VSTPT="2" THEN VSTPTNUM=3;
ELSE IF VSTPT="8" THEN VSTPTNUM=4;
ELSE IF VSTPT="Check-Out" THEN VSTPTNUM=5;

IF VISIT="SCREENING" THEN DO;
VISITNUM=0;
VISIT=UPCASE(VISIT);
END;

IF VISIT="PERIOD-1" THEN DO;
VISITNUM=1;
VISIT=UPCASE(VISIT);
END;

IF VISIT="PERIOD-2" THEN DO;
VISITNUM=2;
VISIT=UPCASE(VISIT);
END;

RUN;

PROC SORT DATA=VS1 OUT=VS2;
BY STUDYID DOMAIN USUBJID VISITNUM VISIT VSTPTNUM VSTPT VSDTC VSDTN;
RUN;

PROC TRANSPOSE DATA=VS2 OUT=VS3;
BY STUDYID DOMAIN USUBJID VISITNUM VISIT VSTPTNUM VSTPT VSDTC VSDTN;
VAR PULSE TEMP SYS DIA;
RUN;

/* STEPS TO CREATE VSTEST VSTESTCD VARIABLES */

DATA VS4;
SET VS3;

LENGTH VSTEST $40. VSTESTCD $8.;
IF _NAME_ = "PULSE" THEN DO;
VSTEST="Pulse Rate";
VSTESTCD="PULSE";
END;

IF _NAME_ = "TEMP" THEN DO;
VSTEST="Temperature";
VSTESTCD="TEMP";
END;

IF _NAME_ = "SYS" THEN DO;
VSTEST="Systolic Blood Pressure";
VSTESTCD="SYSBP";
END;

IF _NAME_ = "DIA" THEN DO;
VSTEST="Diastolic Blood Pressure";
VSTESTCD="DIABP";
END;

VSORRES=STRIP(PUT(COL1,BEST3.));
DROP COL1;

RUN;

/* STEPS TO DERIVE VSORRESU */;

PROC TRANSPOSE DATA=VS2 OUT=VS33;
BY STUDYID DOMAIN USUBJID VISITNUM VISIT VSTPTNUM VSTPT VSDTC VSDTN;
VAR PULSEU TEMPU SYSU DIAU;
RUN;

DATA VS5;
SET VS33;

LENGTH VSTEST VSORRESU $40. VSTESTCD $8.;
IF _NAME_ = "PULSEU" THEN DO;
VSTEST="Pulse Rate";
VSTESTCD="PULSE";
END;

IF _NAME_ = "TEMPU" THEN DO;
VSTEST="Temperature";
VSTESTCD="TEMP";
END;

IF _NAME_ = "SYSU" THEN DO;
VSTEST="Systolic Blood Pressure";
VSTESTCD="SYSBP";
END;

IF _NAME_ = "DIAU" THEN DO;
VSTEST="Diastolic Blood Pressure";
VSTESTCD="DIABP";
END;

VSORRESU=STRIP(COL1);
IF VSORRESU="per min" THEN VSORRESU="beats/min";
ELSE IF VSORRESU="mm of Hg" THEN VSORRESU="mmHg";
ELSE IF VSORRESU="f" THEN VSORRESU="F";

DROP COL1;
VSSTRESU=VSORRESU;
RUN;

/*TO DERIVE VSSTRESC AND VSSTRESN */;

PROC TRANSPOSE DATA=VS2 OUT=VS333;
BY STUDYID DOMAIN USUBJID VISITNUM VISIT VSTPTNUM VSTPT VSDTC VSDTN;
VAR PULSER TEMPR SYSR DIAR;
RUN;

DATA VS6;
SET VS333;
LENGTH VSTEST $40. VSSTRESC $200. VSTESTCD $8.;
IF _NAME_ = "PULSER" THEN DO;
VSTEST="Pulse Rate";
VSTESTCD="PULSE";
END;

IF _NAME_ = "TEMPR" THEN DO;
VSTEST="Temperature";
VSTESTCD="TEMP";
END;

IF _NAME_ = "SYSR" THEN DO;
VSTEST="Systolic Blood Pressure";
VSTESTCD="SYSBP";
END;

IF _NAME_ = "DIAR" THEN DO;
VSTEST="Diastolic Blood Pressure";
VSTESTCD="DIABP";
END;

VSSTRESC=STRIP(COL1);
VSSTRESN=INPUT(VSSTRESC, ?? BEST.);
DROP COL1;
RUN;

PROC SORT DATA=VS4;
BY STUDYID DOMAIN USUBJID VISITNUM VISIT VSTPTNUM VSTPT VSDTC VSDTN VSTESTCD;
RUN;

PROC SORT DATA=VS5;
BY STUDYID DOMAIN USUBJID VISITNUM VISIT VSTPTNUM VSTPT VSDTC VSDTN VSTESTCD;
RUN;

PROC SORT DATA=VS6;
BY STUDYID DOMAIN USUBJID VISITNUM VISIT VSTPTNUM VSTPT VSDTC VSDTN VSTESTCD;
RUN;

DATA FINAL;
MERGE VS4 VS5 VS6;
BY STUDYID DOMAIN USUBJID VISITNUM VISIT VSTPTNUM VSTPT VSDTC VSDTN VSTESTCD;
RUN;

DATA FINAL1;
SET FINAL;
IF VSTPT="0" THEN VSBLFL="Y";
RUN;

/*BRNG-IN DM RAW DATASET TO EXTRACT HT WT BMI INFO*/;

DATA VS_1;
SET RAW.DEMO_RAW1;
STUDYID="765/15";
Domain="VS";
SUBJID=strip(SUBJID);
SITEID="001";
USUBJID=STRIP(STUDYID)||"-"||STRIP(SITEID)||"-"||STRIP(SUBJID);
X=INPUT(ENRDT, MMDDYY10.);
FORMAT X MMDDYY10.;
VSDTC=PUT(X, IS8601DA.)||"T"||PUT(ENRTM, TOD8.);
VSDTN=DATEPART(INPUT(VSDTC, IS8601DT.));
FORMAT VSDTN DATE10.;
DROP X;
IF VISIT="SCREENING" THEN DO;
VISITNUM=0;
VISIT=UPCASE(VISIT);
END;
RUN;

PROC SORT DATA=VS_1 OUT=VS_2;
BY STUDYID DOMAIN USUBJID VISIT VISITNUM VSDTC VSDTN;
RUN;

PROC TRANSPOSE DATA=VS_2 OUT=VS_3;
BY STUDYID DOMAIN USUBJID VISIT VISITNUM VSDTC VSDTN;
VAR HT WT BMI;
RUN;
/*DERIVE VSTEST VSTESTCD VARIABLE FOR THE IMPORTED DM RAW DATASETS*/;

DATA VS_4;
SET VS_3;
LENGTH VSTEST $40.VSTESTCD $8.;
IF _NAME_="HT" THEN DO;
VSTEST="Height";
VSTESTCD="HEIGHT";
END;

IF _NAME_="WT" THEN DO;
VSTEST="Weight";
VSTESTCD="WEIGHT";
END;

IF _NAME_="BMI" THEN DO;
VSTEST="Body Mass Index";
VSTESTCD="BMI";
END;

VSORRES=STRIP(PUT(COL1,BEST3.));
DROP COL1;
RUN;

PROC TRANSPOSE DATA=VS_2 OUT=VS_33;
BY STUDYID DOMAIN USUBJID VISIT VISITNUM VSDTC VSDTN;
VAR HTU WTU BMIU;
RUN;

/*DERIVING VSORRESU AND VSSTRESU VARIABLES*/;
DATA VS_5;
SET VS_33;
LENGTH VSTEST $40. VSORRESU $40. VSTESTCD $8. ;
IF _NAME_="HTU" THEN DO;
VSTEST="Height";
VSTESTCD="HEIGHT";
END;

IF _NAME_="WTU" THEN DO;
VSTEST="Weight";
VSTESTCD="WEIGHT";
END;

IF _NAME_="BMIU" THEN DO;
VSTEST="Body Mass Index";
VSTESTCD="BMI";

END;
VSORRESU=STRIP(COL1);
DROP COL1;

VSSTRESU=VSORRESU;
RUN;

PROC SORT DATA=VS_4;
BY STUDYID DOMAIN USUBJID VISIT VISITNUM VSDTC VSDTN VSTESTCD;
RUN;

PROC SORT DATA=VS_5;
BY STUDYID DOMAIN USUBJID VISIT VISITNUM VSDTC VSDTN VSTESTCD;
RUN;

DATA FINAL_VS;
MERGE VS_4(IN=A) VS_5(IN=B);
BY STUDYID DOMAIN USUBJID VISIT VISITNUM VSDTC VSDTN VSTESTCD;
IF A AND B;
RUN;

/*FINAL VS DATASETS CONTAIN DM AND VS VARIABLES*/;

PROC SORT DATA=FINAL_VS;
BY STUDYID DOMAIN USUBJID VISIT VISITNUM VSDTC VSDTN VSTESTCD;
RUN;

PROC SORT DATA=FINAL1;
BY STUDYID DOMAIN USUBJID VISIT VISITNUM VSDTC VSDTN VSTESTCD;
RUN;

DATA FINALVS;
SET FINAL_VS FINAL1;
RUN;

PROC SORT DATA=FINALVS;
BY STUDYID DOMAIN USUBJID VSTPTNUM VSTPT VISITNUM VISIT VSDTC VSTESTCD ;
RUN;

/*IMPORT DM DATASETS FOR RFSTDTC*/;
DATA DM;
SET SDTM.DM;
RFSTDTN=DATEPART(INPUT(RFSTDTC, IS8601DT.));
FORMAT RFSTDTN DATE10.;
KEEP USUBJID RFSTDTC RFSTDTN;
RUN;

PROC SORT DATA=DM;
BY USUBJID;
RUN;

PROC SORT DATA=FINALVS;
BY USUBJID;
RUN;

DATA DM_VS;
MERGE DM(IN=A) FINALVS (IN=B);
BY USUBJID;
IF B;
RUN;

DATA DM_VS1;
SET DM_VS;
IF RFSTDTN > . AND VSDTN > . THEN DO;
IF VSDTN < RFSTDTN THEN VSDY=RFSTDTN-VSDTN;
ELSE VSDY=RFSTDTN-VSDTN+1;
END;
RUN;

DATA DM_VS2;
SET DM_VS1;
BY STUDYID DOMAIN USUBJID VSTPTNUM VSTPT VISITNUM VISIT VSDTC VSTESTCD;
IF FIRST.USUBJID=1 THEN VSSEQ=1;
ELSE VSSEQ+1;
RUN;

DATA DM_VS22;
SET DM_VS2;
KEEP STUDYID DOMAIN USUBJID VSSEQ VSTESTCD VSTEST VSORRES VSORRESU VSSTRESC VSSTRESN VSSTRESU
VSBLFL VISITNUM VISIT VSDTC VSDY VSTPT VSTPTNUM;
RUN;

PROC SQL;
CREATE TABLE DM_VS222 AS
SELECT
STUDYID 		"Study Identifier" 							LENGTH=8,
DOMAIN			"Domain Abbreviation"						LENGTH=2,
USUBJID			"Unique Subject Identifier"					LENGTH=50,
VSSEQ			"Sequence Number"							LENGTH=8,
VSTESTCD		"Vital Signs Test Short Name"				LENGTH=8,
VSTEST			"Vital Signs Test Name"						LENGTH=40,
VSORRES			"Result or Finding in Original Units"		LENGTH=200,
VSORRESU		"Original Units"							LENGTH=40,
VSSTRESC		"Character Result/Finding in Std Format"	LENGTH=200,
VSSTRESN		"Numeric Result/Finding in Standard Units"	LENGTH=8,
VSSTRESU		"Standard Units"							LENGTH=40,
VSBLFL			"Baseline Flag"								LENGTH=2,
VISITNUM		"Visit Number"								LENGTH=8,
VISIT			"Visit Name"								LENGTH=200,
VSDTC			"Date/Time of Measurements"					LENGTH=25,
VSDY			"Study Day of Vital Signs"					LENGTH=8,
VSTPT			"Planned Time Point Name"					LENGTH=40,
VSTPTNUM		"Planned Time Point Number"					LENGTH=8
FROM DM_VS22;
QUIT;

DATA SDTM.VS(LABEL=Vital Signs);
SET DM_VS222;
RUN;

LIBNAME XPT XPORT "C:\PROJECT\QPS3\SDTM\XPT\XPT_SDTM\VS.XPT";

DATA XPT.VS;
SET DM_VS222;
RUN;
